export const JOBS_DATA = [
  {
    images: "/images/company.png",
    href: "/",
    jobType: "Full Time",
    name: "Email Marketing",
    type: "Agency",
    location: "Jakarta, Indonesia",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui, sunt mollitia. Nemo, illo ratione minima numquam odio inventore adipisci cupiditate sequi maiores perferendis assumenda molestiae expedita, voluptatem eos amet deserunt.",
    categories: ["Marketing", "Email"],
  },
  {
    images: "/images/company.png",
    href: "/",
    jobType: "Full Time",
    name: "Back-End Engineer",
    type: "Agency",
    location: "Jakarta, Indonesia",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui, sunt mollitia. Nemo, illo ratione minima numquam odio inventore adipisci cupiditate sequi maiores perferendis assumenda molestiae expedita, voluptatem eos amet deserunt.",
    categories: ["Engineer", "Back-End"],
  },
  {
    images: "/images/company.png",
    href: "/",
    jobType: "Full Time",
    name: "Front-End Engineer",
    type: "Agency",
    location: "Jakarta, Indonesia",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui, sunt mollitia. Nemo, illo ratione minima numquam odio inventore adipisci cupiditate sequi maiores perferendis assumenda molestiae expedita, voluptatem eos amet deserunt.",
    categories: ["Engineer", "Front-End"],
  },
  {
    images: "/images/company.png",
    href: "/",
    jobType: "Full Time",
    name: "UX Designer",
    type: "Agency",
    location: "Jakarta, Indonesia",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui, sunt mollitia. Nemo, illo ratione minima numquam odio inventore adipisci cupiditate sequi maiores perferendis assumenda molestiae expedita, voluptatem eos amet deserunt.",
    categories: ["Product", "UX", "Designer"],
  },
];
